// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_AssistRepo_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::AssistRepo::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::AssistRepo
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<AssistRepo::implementation::XamlMetaDataProvider>())
    {
    }
}
