// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_AssistRepo_0_H
#define WINRT_AssistRepo_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::AssistRepo
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::AssistRepo::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::AssistRepo::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::AssistRepo::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::AssistRepo::MainWindow> = L"AssistRepo.MainWindow";
    template <> inline constexpr auto& name_v<winrt::AssistRepo::XamlMetaDataProvider> = L"AssistRepo.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::AssistRepo::IMainWindow> = L"AssistRepo.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::AssistRepo::IMainWindow>{ 0x3CA8D949,0x6969,0x5B04,{ 0xA9,0x36,0xE2,0xEE,0xF8,0xD6,0x66,0xFF } }; // 3CA8D949-6969-5B04-A936-E2EEF8D666FF
    template <> struct default_interface<winrt::AssistRepo::MainWindow>{ using type = winrt::AssistRepo::IMainWindow; };
    template <> struct default_interface<winrt::AssistRepo::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::AssistRepo::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_AssistRepo_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::AssistRepo::IMainWindow>
    {
        template <typename D> using type = consume_AssistRepo_IMainWindow<D>;
    };
}
#endif
